### ISSUE TITLE
Recipe in inventory

### ISSUE THREAD

**Issue by EastRane** [Joshcraft2002/joshs-more-foods#21]
After I crafted a pie, I received a notification that I had learned a new recipe. Indeed, the recipe for the “knowledge book” is now displayed in the inventory. But if I click on it, the items are not placed in the crafting grid. This turns the process of crafting a pie into a terrible tedium.

**Comment by Joshcraft2002** [comment]
Do you have any other datapacks, mods, plugins? are you on realms? what version are you on?

**Comment by EastRane** [comment]
> Do you have any other datapacks, mods, plugins? are you on realms? what version are you on?

Initially I experienced this problem on an SMP project with a large number of plugins, but this problem persists even on an empty server with Paper/Purpur.

**Comment by Joshcraft2002** [comment]
Ah wait I think I just got your question, you are using minecraft's recipe book to automatically move items into the crafting grid, yes?

If that's the case, you can't really do it that way for perhaps most datapacks since you don't just "craft" knowledge books, you kinda have to place the items into the grid yourself.

**Comment by EastRane** [comment]
thank you
